-- MySQL Script generated by MySQL Workbench
-- Fri Mar 14 22:06:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Студенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`студенты` (
  `idСтудента` INT NOT NULL AUTO_INCREMENT,
  `ФИО` VARCHAR(100) NOT NULL,
  `Факультет` VARCHAR(100) NOT NULL,
  `Номер_телефона` VARCHAR(20) NOT NULL,
  `Номер_комнаты` INT NOT NULL,
  `Дата_заселения` DATE NOT NULL,
  `Дата_выселения` DATE NOT NULL,
  `Статус_проживания` VARCHAR(45) NOT NULL,
  `Размер_оплаты` INT NOT NULL,
  `Дата_последнего_платежа` DATE NOT NULL,
  `Долг` INT NOT NULL,
  PRIMARY KEY (`idСтудента`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'СОЗДАТЬ ТАБЛИЦУ Студенты *( Хранит информацию о студентах, \nпроживающих в общежитии )\n ПЕРВИЧНЫЙ КЛЮЧ ( ID_Студента )\n ВНЕШНИЙ КЛЮЧ ( Номер_комнаты ИЗ Комнаты\n NULL-значения НЕ ДОПУСТИМЫ )\n ПОЛЯ ( ID_Студента Целое, ФИО Строка, Факультет Строка,\n Номер_телефона Строка, Номер_комнаты Целое, Дата_заселения Дата,\n Дата_выселения Дата, Статус_проживания Строка, Размер_оплаты Целое,\n Дата_последнего_платежа Дата, Долг Целое )\n ОГРАНИЧЕНИЯ (\n Значение Долг не может быть отрицательным.\n Статус_проживания может принимать только значения: \"Проживает\", \"В \nотъезде\", \"Выселен\".\n Дата_выселения не может быть раньше Дата_заселения.\n )';


-- -----------------------------------------------------
-- Table `mydb`.`Студенты_комнаты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`студенты_комнаты` (
  `Номер_комнаты` INT NOT NULL,
  `idСтудента` INT NOT NULL,
  PRIMARY KEY (`Номер_комнаты`, `idСтудента`),
  INDEX `fk_Студенты_комнаты_Студенты1_idx` (`idСтудента` ASC) VISIBLE,
  CONSTRAINT `fk_Студенты_комнаты_Студенты1`
    FOREIGN KEY (`idСтудента`)
    REFERENCES `mydb`.`студенты` (`idСтудента`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Комнаты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`комнаты` (
  `Этаж` INT NOT NULL,
  `Состояние_комнаты` VARCHAR(45) NOT NULL,
  `Количество_мест` INT NOT NULL,
  `Свободные_места` INT NOT NULL,
  `Студенты_комнаты_Номер_комнаты` INT NOT NULL,
  PRIMARY KEY (`Студенты_комнаты_Номер_комнаты`),
  CONSTRAINT `fk_Комнаты_Студенты_комнаты1`
    FOREIGN KEY (`студенты_комнаты_Номер_комнаты`)
    REFERENCES `mydb`.`студенты_комнаты` (`Номер_комнаты`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`нарушения`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`нарушения` (
  `idНарушения` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(45) NOT NULL,
  `Санкция` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idНарушения`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = ' СОЗДАТЬ ТАБЛИЦУ Нарушения *( Хранит возможные нарушения \nправил проживания в общежитии )\n ПЕРВИЧНЫЙ КЛЮЧ ( ID_Нарушения )\n ПОЛЯ ( ID_Нарушения Целое, Название Строка, Санкция Строка )\n ОГРАНИЧЕНИЯ (\n Название нарушения должно быть уникальным.\n Санкция может принимать значения: \"Предупреждение\", \"Штраф\", \n\"Выселение\", \"Лишение доп. техники\".\n )';


-- -----------------------------------------------------
-- Table `mydb`.`Студенты_нарушения`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`студенты_нарушения` (
  `Дата_нарушения` DATE NOT NULL,
  `idСтудента` INT NOT NULL,
  `idНарушения` INT NOT NULL,
  PRIMARY KEY (`idСтудента`, `idНарушения`),
  INDEX `fk_Студенты_нарушения_Нарушения1_idx` (`idНарушения` ASC) VISIBLE,
  CONSTRAINT `fk_Студенты_нарушения_Студенты1`
    FOREIGN KEY (`idСтудента`)
    REFERENCES `mydb`.`студенты` (`idСтудента`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Студенты_нарушения_Нарушения1`
    FOREIGN KEY (`idНарушения`)
    REFERENCES `mydb`.`нарушения` (`idНарушения`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = ' СОЗДАТЬ ТАБЛИЦУ Студенты_Нарушения *( Фиксирует нарушения, \nсовершенные студентами )\n ПЕРВИЧНЫЙ КЛЮЧ ( ID_Студента, ID_Нарушения, Дата_нарушения )\n ВНЕШНИЙ КЛЮЧ ( ID_Студента ИЗ Студенты\n NULL-значения НЕ ДОПУСТИМЫ )\n ВНЕШНИЙ КЛЮЧ ( ID_Нарушения ИЗ Нарушения\n NULL-значения НЕ ДОПУСТИМЫ )\n ПОЛЯ ( ID_Студента Целое, ID_Нарушения Целое )';


-- -----------------------------------------------------
-- Table `mydb`.`техника`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Техника` (
  `idТехники` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idТехники`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'СОЗДАТЬ ТАБЛИЦУ Техника *( Хранит информацию о доступной \nтехнике в общежитии )\n ПЕРВИЧНЫЙ КЛЮЧ ( ID_Техники )\n ПОЛЯ ( ID_Техники Целое, Название Строка )\n ОГРАНИЧЕНИЯ (\n Название техники должно быть уникальным.\n )';


-- -----------------------------------------------------
-- Table `mydb`.`Студенты_техника`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`студенты_техника` (
  `Состояние техники` VARCHAR(45) NOT NULL,
  `idСтудента` INT NOT NULL,
  `idТехники` INT NOT NULL,
  PRIMARY KEY (`idСтудента`, `idТехники`),
  INDEX `fk_Студенты_техника_Техника1_idx` (`idТехники` ASC) VISIBLE,
  CONSTRAINT `fk_Студенты_техника_Студенты1`
    FOREIGN KEY (`idСтудента`)
    REFERENCES `mydb`.`студенты` (`idСтудента`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Студенты_техника_Техника1`
    FOREIGN KEY (`idТехники`)
    REFERENCES `mydb`.`техника` (`idТехники`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'СОЗДАТЬ ТАБЛИЦУ Студенты_Техника *( Связывает студентов с \nтехникой, которой они пользуются )\n ПЕРВИЧНЫЙ КЛЮЧ ( ID_Студента, ID_Техники )\n ВНЕШНИЙ КЛЮЧ ( ID_Студента ИЗ Студенты\n NULL-значения НЕ ДОПУСТИМЫ )\n ВНЕШНИЙ КЛЮЧ ( ID_Техники ИЗ Техника\n NULL-значения НЕ ДОПУСТИМЫ )\n ПОЛЯ ( ID_Студента Целое, ID_Техники Целое )';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
